name: E2E Node.js

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'
        node:
          - 16

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g npm

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.8.5"

      - name: Install vessel
        run: |
          set -x
          curl --location --output vessel-linux64 "https://github.com/dfinity/vessel/releases/download/v0.6.2/vessel-linux64"
          mkdir $HOME/bin
          mv ./vessel-linux64 $HOME/bin/vessel
          chown -R "$(whoami)" $HOME/bin && chmod -R +x $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run make e2e
        run: |
          set -x
          make e2e
